# Arreglos

In [26]:
from numpy import *
def nombre (variable1, variable2):
  return array([variable1,variable2])

In [27]:
nombre(0,0)

array([0, 0])

In [28]:
def promedio(l):
  n=len(l)
  s=0
  for i in range(n):
    s+=l[i]
  return s/n

In [29]:
promedio([1,2,3])

2.0

In [30]:
def punto(l1,l2):
  n1=len(l1)
  n2=len(l2)
  if n1!=n2:
    return 'Vectores con dimensión distinta'
  else:
    s=0
    for i in range(n2):
      s+=l1[i]*l2[i]
    return s

In [31]:
punto([0,1],[0,5])

5

In [32]:
import numpy as np

v1=np.array([1,2,3,4,5],float) #complex
v2=np.array([10,20,30,40,50])
print(v1)
print(v1+v2)
print(v1*v2)

[1. 2. 3. 4. 5.]
[11. 22. 33. 44. 55.]
[ 10.  40.  90. 160. 250.]


In [33]:
#creación de una lista llena de ceros
lista_ceros=[0]*3
print(lista_ceros)
#para hacer una lista de listas, por ejemplo de 4x3 llena de ceros
ll_ceros=[]
for i in range(4): #hacemos los renglones
  ll_ceros.append([0]*3)
print(ll_ceros)
#la podemos hacer arreglo
ll_ceros=array(ll_ceros)
print(ll_ceros)

[0, 0, 0]
[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
#Pero, tenemos unas funciones en numpy para hacer arreglos llenos de ceros
import numpy as n
a1=n.zeros(3) #arreglo orden 1, dimension 3
print(a1)
a2=n.zeros([3,3,3]) #arreglo orden 3, dimension 3
print(a2)
a3=n.ones([5,2],complex) #arreglo orden 2, 5 renglones-2 columnas
print(a3)
a4=eye(4) #identidad, por fuerza tiene que ser float
print(a4)

[0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#función idéntidad compleja
import numpy as n

def complex_eye(m):
  z=n.zeros([m,m],complex)
  for i in range(m):
    #for j in range(m):
      #if i==j: #elementos de la diagonal
        z[i,i]=1+1j
  return z
print(complex_eye(5))

[[1.+1.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+1.j]]


In [36]:
import numpy as np
k1=int(input('Da el no. de renglones'))
k2=int(input('Da el no. de columnas'))
A=np.empty([k1,k2],float)
for i in range(k1):
  for j in range(k2):
    A[i,j]=float(input('Da el elemento (%d,%d)'%(i,j)))
print(A)

Da el no. de renglones3
Da el no. de columnas2
Da el elemento (0,0)1
Da el elemento (0,1)2
Da el elemento (1,0)3
Da el elemento (1,1)4
Da el elemento (2,0)5
Da el elemento (2,1)6
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [37]:
import numpy as np

def genera_matriz():
  k1=int(input('Da el no. de renglones'))
  k2=int(input('Da el no. de columnas'))
  A=np.empty([k1,k2],float)
  for i in range(k1):
    for j in range(k2):
      A[i,j]=float(input('Da el elemento (%d,%d)'%(i,j)))
  return A
A=genera_matriz()
print(A)

Da el no. de renglones2
Da el no. de columnas1
Da el elemento (0,0)1
Da el elemento (1,0)2
[[1.]
 [2.]]


In [38]:
print(A[0])
print('no. de renglones',len(A))
print('no. de columnas',len(A[0]))

[1.]
no. de renglones 2
no. de columnas 1


In [39]:
#hagamos una funcion que evalue el tipo de elemento que recibe y actua en consecuencia
from numpy import *
def tipo(l1,l2):
  if isinstance(l1,float)==True or isinstance(l1,int)==True:
    return "escalar"
  elif isinstance(l1,list)==True:
    return "vector"
  else:# isinstance(l1,array)==True:
    return "arreglo"
print(tipo(3,4))
print(tipo([1,2,3],[4,5,6]))
A1=array([[1,2,3],[4,5,6]])
A2=array([[10,20,30],[40,50,60]])
print(tipo(A1,A2))

escalar
vector
arreglo


In [40]:
#Usamos la estructura de la función anterior para incorporar el producto matricial en la función producto punto
from numpy import *

def punto(l1,l2):
  if isinstance(l1,float)==True or isinstance(l1,int)==True:
    return l1*l2
  elif isinstance(l1,list)==True:
    if len(l1)!=len(l2):
      return 'vectores con dimensiones incompatibles'
    elif len(l1)==len(l2):
      s=0
      dim_l1=len(l1)
      for i in range(dim_l1):
        s+=l1[i]*l2[i]
      return s
  else:
    #saquemos las dimensiones de las matrices l1 y l2
    l1_ren=len(l1)
    l1_col=len(l1[0])
    l2_ren=len(l2)
    l2_col=len(l2[0])
    if l1_col!=l2_ren:
      return 'Matrices con dimensiones incompatibles'
    elif l1_col==l2_ren:
      C=zeros([l1_ren,l2_col])
      for i in range(l1_ren):
        for j in range(l2_ren):
          for k in range(l2_col):
            C[i,j]+=l1[i,k]*l2[k,j]
      return C
A1=array([[1,2,3],[4,5,6],[7,8,9]])
A2=array([[10,20,30],[40,50,60],[70,80,90]])
print(punto(A1,A2))

[[ 300.  360.  420.]
 [ 660.  810.  960.]
 [1020. 1260. 1500.]]


In [41]:
#Vamos a probar la matriz

print(punto(3,4))
print(punto([1,2,3],[4]))
print(punto([1,2,3],[4,5,6]))
M1=array([[1,2,3],[4,5,6],[7,8,9]])
M2=array([[1,1,1]])
print(punto(M1,M2))
A1=array([[1,2,3],[4,5,6],[7,8,9]])
A2=array([[10,20,30],[40,50,60],[70,80,90]])
print(punto(A1,A2))

12
vectores con dimensiones incompatibles
32
Matrices con dimensiones incompatibles
[[ 300.  360.  420.]
 [ 660.  810.  960.]
 [1020. 1260. 1500.]]
